services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/tournament
      - JWT_SECRET=TEST_SECRET
    volumes:
      - .:/app
      - /app/node_modules
    command: ["pnpm", "dev"]
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
